config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('customers/', include('customers.urls', namespace='customers'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from .views import customer_list, add_customer, edit_customer, delete_customer, customer_detail, export_data

app_name = 'customers'

urlpatterns = [
    path('customers/', customer_list, name='customer_list'),
    path('customers/add/', add_customer, name='add_customer'),
    path('customers/<int:pk>/edit',  edit_customer, name='edit_customer'),
    path('customers/<int:pk>/delete', delete_customer, name = 'delete_customer'),
    path('customers/<int:pk>/', customer_detail, name='customer_detail'),
    path('export/', export_data, name='export_data'),
]

shop/urls.py
from django.urls import path
from .views import Home, ProductDetail, ProductList, ProductGrid, CategoryDetail, AddReview
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetail.as_view(), name='product_details'),
    path('products/<slug:category_slug>/', Home.as_view(), name='get_all_products_by_category'),
    path('products/', ProductList.as_view(), name='product_list'),
    path('product-grid/', ProductGrid.as_view(), name='product_grid'),
    path('category/<int:pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('product/<int:product_id>/add_review/', AddReview.as_view(), name='add_review'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Customer(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = PhoneNumberField(region = 'UZ', blank=True, null=True)
    address = models.TextField(blank=True)
    joined = models.DateTimeField()

    def __str__(self):
        return self.full_name

class CustomerLog(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='logs')
    status_code = models.IntegerField()
    endpoint = models.CharField(max_length=255)
    timestamp = models.DateTimeField()

    def __str__(self):
        return f'{self.customer} - {self.status_code} {self.endpoint}'

customers/forms.py
from django import forms
from customers.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['full_name', 'email', 'phone', 'address']

customers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Customer
from .forms import CustomerForm
from django.http import HttpResponse
import csv
import json
from django.views.generic import ListView,DetailView



def customer_list(request):
    customers = Customer.objects.all()
    return render(request, 'customers/customer_list.html', {'customers': customers})


def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    logs = getattr(customer, 'logs', None)
    if logs:
        logs = logs.order_by('-timestamp')[:10]
    return render(request, 'customers/customers_detail.html', {'customer': customer, 'logs': logs})


def add_customer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('customers:customer_list')
    else:
        form = CustomerForm()
    return render(request, 'customers/customers_detail.html', {'form': form, 'customer': None})


def edit_customer(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customers:customer_list')
    else:
        form = CustomerForm(instance=customer)
    
    return render(request, 'customers/customers_detail.html', {'form': form, 'customer': customer})


def delete_customer(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        customer.delete()
        return redirect('customers:customer_list')
    return render(request, 'customers/customers_detail.html', {'customer': customer})


def export_data(request):
    file_type = request.GET.get('file_type')
    if file_type == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="customers.csv"'

        writer = csv.writer(response)
        writer.writerow(['ID','FULL NAME','EMAIL','PHONE NUMBER','ADDRESS','JOINED'])

        customers = Customer.objects.all().values_list('id','full_name','email','phone','address','joined')
        for customer in customers:
            writer.writerow(customer)

        return response

    elif file_type == 'json':
        response = HttpResponse(content_type='application/json')
        data = list(Customer.objects.all().values('id','full_name', 'email', 'phone', 'address','joined'))
        response.write(json.dumps(data, indent=4,default=str))
        response['Content-Disposition'] = 'attachment; filename=customers.json'
        return response
    
    elif file_type == 'excel':
        response = HttpResponse(content_type='text/tab-separated=values')
        response['Content-Dispoition'] = 'attachment; filename="customers.xls"'

        writer = csv.writer(response, delimiter='\t')
        writer.writerow(['ID', 'FULL_NAME', 'EMAIl', 'PHONE NUMBER', 'ADDRESS', 'JOINED'])

        customers = Customer.objects.all().values_list('id', 'full_name', 'email', 'phone', 'address', 'joined')
        for customer in customers:
            writer.writerow(customer)

        return response

customers/templates/customers/customer_list.html
{%extends 'shop/base/base.html' %}


{%block customer_content%}
<div class="card mb-3" id="customersTable" data-list='{"valueNames":["name","email","phone","address","joined"],"page":10,"pagination":true}'>
            <div class="card-header">
              <div class="row flex-between-center">
                <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                  <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">Customers</h5>
                </div>
                <div class="col-8 col-sm-auto text-end ps-2">
                  <div class="d-none" id="table-customers-actions">
                    <div class="d-flex">
                      <select class="form-select form-select-sm" aria-label="Bulk actions">
                        <option selected="">Bulk actions</option>
                        <option value="Refund">Refund</option>
                        <option value="Delete">Delete</option>
                        <option value="Archive">Archive</option>
                      </select>
                      <button class="btn btn-falcon-default btn-sm ms-2" type="button">Apply</button>
                    </div>
                  </div>
                  <div id="table-customers-replace-element">
                    <button class="btn btn-falcon-default btn-sm" type="button"><span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ms-1">New</span></button>
                    <button class="btn btn-falcon-default btn-sm mx-2" type="button"><span class="fas fa-filter" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ms-1">Filter</span></button>
                    <form action="{% url 'customers:export_data' %}">
                      <button class="btn btn-falcon-default btn-sm" type="submit">
                        <span class="fas fa-external-link-alt" data-fa-transform="shrink-3 down-2"></span>
                        <span class="d-none d-sm-inline-block ms-1">Export</span>
                      </button>
                      <select class="form-select" aria-label="Default select example" name="file_type">
                          <option selected value=none>...</option>
                          <option value="json">JSON</option>
                          <option value="csv">CSV</option>
                          <option value="excel">EXCEL</option>
                      </select>
                  </form>
                  </div>
                </div>
              </div>
            </div>
            <div class="card-body p-0">
              <div class="table-responsive">
                <table class="table table-sm table-striped fs--1 mb-0 overflow-hidden">
                  <thead class="bg-200 text-900">
                    <tr>
                      <th>
                        <div class="form-check fs-0 mb-0 d-flex align-items-center">
                          <input class="form-check-input" id="checkbox-bulk-customers-select" type="checkbox" data-bulk-select='{"body":"table-customers-body","actions":"table-customers-actions","replacedElement":"table-customers-replace-element"}' />
                        </div>
                      </th>
                      <th class="sort pe-1 align-middle white-space-nowrap" data-sort="name">Name</th>
                      <th class="sort pe-1 align-middle white-space-nowrap" data-sort="email">Email</th>
                      <th class="sort pe-1 align-middle white-space-nowrap" data-sort="phone">Phone</th>
                      <th class="sort pe-1 align-middle white-space-nowrap ps-5" data-sort="address" style="min-width: 200px;">Billing Address</th>
                      <th class="sort pe-1 align-middle white-space-nowrap" data-sort="joined">Joined</th>
                      <th class="align-middle no-sort"></th>
                    </tr>
                  </thead>
                  <tbody class="list" id="table-customers-body">
                    {% for customer in customers%}
                      <tr class="btn-reveal-trigger">
                        <td class="align-middle py-2" style="width: 28px;">
                          <div class="form-check fs-0 mb-0 d-flex align-items-center">
                            <input class="form-check-input" type="checkbox" id="customer-0" data-bulk-select-row="data-bulk-select-row" />
                          </div>
                        </td>
                        <td class="name align-middle white-space-nowrap py-2"><a href="{%url 'customers:customer_detail' customer.id%}">
                            <div class="d-flex d-flex align-items-center">
                              <div class="avatar avatar-xl me-2">
                                <div class="avatar-name rounded-circle"><span>RA</span></div>
                              </div>
                              <div class="flex-1">
                                <h5 class="mb-0 fs--1">{{customer.full_name}}</h5>
                              </div>
                            </div>
                          </a></td>
                        <td class="email align-middle py-2"><a href="mailto:ricky@example.com">{{customer.email}}</a></td>
                        <td class="phone align-middle white-space-nowrap py-2"><a href="tel:2012001851">{{customer.phone}}</a></td>
                        <td class="address align-middle white-space-nowrap ps-5 py-2">{{customer.address}}</td>
                        <td class="joined align-middle py-2">{{customer.joined}}</td>
                        <td class="align-middle white-space-nowrap py-2 text-end">
                          <div class="dropdown font-sans-serif position-static">
                            <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal" type="button" id="customer-dropdown-0" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h fs--1"></span></button>
                            <div class="dropdown-menu dropdown-menu-end border py-0" aria-labelledby="customer-dropdown-0">
                              <div class="bg-white py-2"><a class="dropdown-item" href="#!">Edit</a><a class="dropdown-item text-danger" href="#!">Delete</a></div>
                            </div>
                          </div>
                        </td>
                      </tr>
                    {%endfor%}
                    
                   
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-center">
              <button class="btn btn-sm btn-falcon-default me-1" type="button" title="Previous" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
              <ul class="pagination mb-0"></ul>
              <button class="btn btn-sm btn-falcon-default ms-1" type="button" title="Next" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>
            </div>
          </div>
{% endblock %}