config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('customers/', include('customers.urls', namespace='customers'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import Home, ProductDetail, ProductList, ProductGrid, CategoryDetail, AddReview
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetail.as_view(), name='product_details'),
    path('products/<slug:category_slug>/', Home.as_view(), name='get_all_products_by_category'),
    path('products/', ProductList.as_view(), name='product_list'),
    path('product-grid/', ProductGrid.as_view(), name='product_grid'),
    path('category/<int:pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('product/<int:product_id>/add_review/', AddReview.as_view(), name='add_review'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from django.utils.text import slugify


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, null=True, blank=True)

    class Meta:
        abstract = True
        # proxy = True

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Categories/', null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # if self.slug is None:
        self.slug = slugify(self.name)
        super(Category,self).save(*args, **kwargs)


    def __str__(self):
        return self.name


class Product(BaseModel):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    main_image = models.ImageField(upload_to='products/main/', blank=True, null=True)
    long_description = models.TextField(blank=True, null=True)
    code = models.CharField(max_length=255, null=True, blank=True)


    def __str__(self):
        return self.name
    
    @property
    def main_image_url(self):
        main_img = self.images.filter(is_main=True).first()
        if main_img:
            return main_img.image.url
        elif self.main_image:
            return self.main_image.url
        return '/static/users/assets/img/default-product.jpg' 


    @property
    def discounted_price(self):
        if self.discount > 0:
            discount_amount = self.price * Decimal(self.discount) / Decimal(100)
            return self.price - discount_amount
        return self.price

    class Meta:
        ordering = ['my_order']
        verbose_name = 'product'
        verbose_name_plural = 'products'

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name = 'images')
    image = models.ImageField(upload_to='products/gallery/')
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product.name} - Image"

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    author = models.CharField(max_length=100)
    email = models.EmailField()
    rating = models.DecimalField(max_digits=2, decimal_places=1) 
    title = models.CharField(max_length=255, blank=True, null=True)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} - {self.product.name} ({self.rating})"


class AttributeKey(BaseModel):
    key_name = models.CharField(max_length=50,unique=True)
    
    def __str__(self):
        return self.key_name
   
class AttributeValue(BaseModel):
    value_name = models.CharField(max_length=255,unique=True)
    
    def __str__(self):
        return self.value_name
    
class Attribute(BaseModel):
    attribute_key = models.ForeignKey(AttributeKey,on_delete=models.CASCADE)
    attribute_value = models.ForeignKey(AttributeValue,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='attributes')
    
    def __str__(self):
        return f'{self.product.name} - {self.attribute_key.key_name} - {self.attribute_value.value_name}'

shop/forms.py
from django import forms
from .models import Product, Review

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'main_image', 'discount', 'category', 'quantity']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['author', 'email', 'rating', 'content']

        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email address'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 5}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Your review'}),
        }

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Category, Review
from decimal import Decimal
from django.views import View
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator


# def home(request):
#     search_query = request.GET.get('q', '')
#     category_id = request.GET.get('category')

#     categories = Category.objects.all()
#     products = Product.objects.all()

#     if category_id:
#         products = products.filter(category_id=category_id)

#     if search_query:
#         products = products.filter(name__icontains=search_query)

#     context = {
#         'products': products,
#         'categories': categories,
#         'selected_category_id': int(category_id) if category_id else None
#     }
#     return render(request, 'shop/home.html', context)


class Home(View):
    def get(self, request, category_slug=None):
        categories = Category.objects.all()
        products = Product.objects.all()
        paginator = Paginator(products, 3)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {
            'categories': categories,
            'page_obj' : page_obj
        }
        if category_slug:
            products = Product.objects.filter(category__slug = category_slug)
            context = {
                'products': products,
            }
            return render(request, 'shop/product-list.html', context)
    
        return render(request,'shop/home.html',context)

        
        

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['categories'] = Category.objects.all()
    #     context['products'] = Product.objects.all()
    #     return context


# def category_detail(request, pk):
#     category = get_object_or_404(Category, pk=pk)
#     products = category.products.all()
#     return render(request, 'shop/category_detail.html', {'category': category, 'products': products})

class CategoryDetail(View):
    def get(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        products = category.products.all()
        return render(request, 'shop/category_detail.html', {'category': category, 'products': products})


# def product_details(request, product_id):
#     product = get_object_or_404(Product, id=product_id)
#     main_image = product.images.filter(is_main=True).first()
#     gallery_images = product.images.exclude(is_main=True)
#     reviews = product.reviews.order_by('-date')
    

#     context = {
#         'product': product,
#         'main_image': main_image,
#         'gallery_images': gallery_images,
#         'reviews': reviews,
#     }
#     return render(request, 'shop/detail.html', context)


class ProductDetail(View):
    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        main_image = product.images.filter(is_main=True).first()
        gallery_images = product.images.exclude(is_main=True)
        reviews = product.reviews.order_by('-date')

        context = {
            'product': product,
            'main_image': main_image,
            'gallery_images': gallery_images,
            'reviews': reviews,
        }
        return render(request, 'shop/detail.html', context)



# def product_grid(request):
#     products = Product.objects.all()
#     return render(request, 'shop/product-grid.html', {'products': products})

class ProductGrid(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'shop/product-grid.html', {'products': products})


# def add_review(request, product_id):
#     product = get_object_or_404(Product, id=product_id)

#     if request.method == 'POST':
#         rating = request.POST.get('rating')
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         review_text = request.POST.get('review')

#         if rating and name and email and review_text:
#             Review.objects.create(
#                 product=product,
#                 rating=Decimal(rating),
#                 author=name,
#                 email=email,
#                 content=review_text,
#             )

#     return redirect('shop:detail.html', product_id=product.id)


class AddReview(CreateView):
    model = Product
    template_name = 'shop/product/detail.html'
    success_url = reverse_lazy('shop:home')


# def product_list(request):
#     category_id = request.GET.get('category')

#     if category_id:
#         products = Product.objects.filter(category_id=category_id)
#     else:
#         products = Product.objects.all()

#     categories = Category.objects.all()
#     context = {
#         'products': products,
#         'categories': categories,
#     }

#     return render(request, 'shop/product-list.html', context)


class ProductList(View):
    def get(self, request):
        category_id = request.GET.get('category')

        if category_id:
            products = Product.objects.select_related('category',).filter(category_id=category_id)
        else:
            products = Product.objects.select_related('category',).all()

        categories = Category.objects.all()
        context = {
            'products': products,
            'categories': categories,
        }
        return render(request, 'shop/product-list.html', context)

shop/templates/shop/home.html
{%extends 'shop/base/base.html' %}
{%load static%}


{%block title%}
  Shop
{%endblock%}


{%block main_content%}
<div class="card mt-2 mb-2">
            <div class="card-header bg-light">
              <div class="row align-items-center">
                <div class="col">
                  <h5 class="mb-0" id="followers"></h5>
                </div>
                <div class="col text-end"><a class="font-sans-serif" href="./app/social/followers.html">Kategoriyalar</a>
                </div>
              </div>
            </div>
            <div class="card-body bg-light px-1 py-0">
              <div class="row g-0 text-center fs--1">
                {% for category in categories%}
                  <div class="col-4 col-md-4 col-lg-3 col-xx1-2 mb-1">
                    <div class="bg-white dark__bg-1100 p-1 h-100">
                      <a href="{% url 'shop:get_all_products_by_category' category.slug %}">
                        <img class="img-thumbnail img-fluid  mb-3 shadow-sm" src="{{category.image.url}}" alt="" width="100">
                      </a>
                      <h6 class="mb-1"><a href="#">{{category.name}}</a>
                      </h6>
                      <p class="fs--2 mb-1"></p>
                    </div>
                  </div>
                {%endfor%}
              </div>
            </div>
</div>

<div class="card mb-3">
            <div class="card-body">
              <div class="row">
                {% for product in page_obj%}
                  <div class="col-6 mb-3 col-md-6 col-lg-4">
                    <div class="border rounded-1 d-flex flex-column justify-content-between pb-3">
                      <div class="overflow-hidden">
                        <div class="position-relative rounded-top overflow-hidden"><a class="d-block" href="{% url 'shop:product_details' product.id %}"><img class="img-fluid rounded-top" src="{{product.images.first.image.url}}" alt=""></a>
                        </div>
                          <div class="p-2">
                            <h5 class="fs-0"><a class="text-dark" href="{% url 'shop:product_details' product.id %}">{{product.name}} </a></h5>
                            <p class="fs--1 mb-2"><a class="text-500" href="#!">{{product.category.title}}</a></p>
                            <h5 class="fs-md-2 text-warning mb-0 d-flex align-items-center mb-2"> {{product.price}} so'm
                              <!-- <del class="ms-2 fs--1 text-500">180 000 so'm </del> -->
                            </h5>
                            </p>
                          </div>
                      </div>
                      <div class="d-flex flex-between-center px-3">
                        
                        <div><a class="btn btn-sm btn-falcon-default" style="width: 130px;" href="#!" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Add to Cart" aria-label="Add to Cart"><svg class="svg-inline--fa fa-cart-plus fa-w-18" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="cart-plus" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M504.717 320H211.572l6.545 32h268.418c15.401 0 26.816 14.301 23.403 29.319l-5.517 24.276C523.112 414.668 536 433.828 536 456c0 31.202-25.519 56.444-56.824 55.994-29.823-.429-54.35-24.631-55.155-54.447-.44-16.287 6.085-31.049 16.803-41.548H231.176C241.553 426.165 248 440.326 248 456c0 31.813-26.528 57.431-58.67 55.938-28.54-1.325-51.751-24.385-53.251-52.917-1.158-22.034 10.436-41.455 28.051-51.586L93.883 64H24C10.745 64 0 53.255 0 40V24C0 10.745 10.745 0 24 0h102.529c11.401 0 21.228 8.021 23.513 19.19L159.208 64H551.99c15.401 0 26.816 14.301 23.403 29.319l-47.273 208C525.637 312.246 515.923 320 504.717 320zM408 168h-48v-40c0-8.837-7.163-16-16-16h-16c-8.837 0-16 7.163-16 16v40h-48c-8.837 0-16 7.163-16 16v16c0 8.837 7.163 16 16 16h48v40c0 8.837 7.163 16 16 16h16c8.837 0 16-7.163 16-16v-40h48c8.837 0 16-7.163 16-16v-16c0-8.837-7.163-16-16-16z"></path></svg><!-- <span class="fas fa-cart-plus"></span> Font Awesome fontawesome.com --></a></div>
                      </div>
                    </div>
                  </div>
                {%endfor%}
                                              

              </div>
            </div>
            <div class="card-footer bg-light d-flex justify-content-center">
              <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
              </div>
            </div>
          </div>

{%endblock%}

shop/templates/shop/product-list.html
{% extends 'shop/base/base.html' %}
{%load static%}


{%block title%}
  All Products
{%endblock%}

{%block product_list%}
<div class="card mb-3">
            <div class="card-body">
              <div class="row flex-between-center">
                <div class="col-sm-auto mb-2 mb-sm-0">
                  <h6 class="mb-0">Showing 1-24 of 205 Products</h6>
                </div>
                <div class="col-sm-auto">
                  <div class="row gx-2 align-items-center">
                    <div class="col-auto">
                      <form class="row gx-2">
                        <div class="col-auto"><small>Sort by: </small></div>
                        <div class="col-auto">
                          <select class="form-select form-select-sm" aria-label="Bulk actions">
                            <option selected="">Best Match</option>
                            <option value="Refund">Newest</option>
                            <option value="Delete">Price</option>
                          </select>
                        </div>
                      </form>
                    </div>
                    <div class="col-auto pe-0"><a class="text-600 px-1" href="../../../app/e-commerce/product/product-grid.html" data-bs-toggle="tooltip" title="Product Grid"><span class="fas fa-th"></span></a></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-body p-0 overflow-hidden">
              <div class="row g-0">
                {%for product in products%}
                  <div class="col-12 p-card">
                    <div class="row">
                      <div class="col-sm-5 col-md-4">
                        <div class="position-relative h-sm-100"><a class="d-block h-100" href="{% url 'shop:product_details' product.id %}"><img class="img-fluid fit-cover w-sm-100 h-sm-100 rounded-1 absolute-sm-centered" src="{{product.images.first.image.url}}" alt="" /></a>
                          <div class="badge rounded-pill bg-success position-absolute top-0 end-0 me-2 mt-2 fs--2 z-index-2">New</div>
                        </div>
                      </div>
                      <div class="col-sm-7 col-md-8">
                        <div class="row">
                          <div class="col-lg-8">
                            <h5 class="mt-3 mt-sm-0"><a class="text-dark fs-0 fs-lg-1" href="{% url 'shop:product_details' product.id %}">{{product.name}}</a></h5>
                            <p class="fs--1 mb-2 mb-md-3"><a class="text-500" href="#!">{{product.category.title}}</a></p>
                            <ul class="list-unstyled d-none d-lg-block">
                              {%for attr in product.attributes.all%}
                                <li><span class="fas fa-circle" data-fa-transform="shrink-12"></span><span>{{attr.attribute_value.value_name}}</span></li>
                              {%endfor%}
                            </ul>
                          </div>
                          <div class="col-lg-4 d-flex justify-content-between flex-column">
                            <div>
                              <h4 class="fs-1 fs-md-2 text-warning mb-0">${{product.price}}</h4>
                              <h5 class="fs--1 text-500 mb-0 mt-1">
                                <del>$2399 </del><span class="ms-1">-{{product.discount}}%</span>
                              </h5>
                              <div class="mb-2 mt-3"><span class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span class="fa fa-star text-300"></span><span class="ms-1">(8)</span>
                              </div>
                              <div class="d-none d-lg-block">
                                <p class="fs--1 mb-1">Shipping Cost: <strong>$50</strong></p>
                                <p class="fs--1 mb-1">Stock: <strong class="text-success">Available</strong>
                                </p>
                              </div>
                            </div>
                            <div class="mt-2"><a class="btn btn-sm btn-outline-secondary border-300 d-lg-block me-2 me-lg-0" href="#!"><span class="far fa-heart"></span><span class="ms-2 d-none d-md-inline-block">Favourite</span></a><a class="btn btn-sm btn-primary d-lg-block mt-lg-2" href="#!"><span class="fas fa-cart-plus"> </span><span class="ms-2 d-none d-md-inline-block">Add to Cart</span></a></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                {%endfor%}
               
              </div>
            </div>
            <div class="card-footer border-top d-flex justify-content-center">
              <button class="btn btn-falcon-default btn-sm me-2" type="button" disabled="disabled" data-bs-toggle="tooltip" data-bs-placement="top" title="Prev"><span class="fas fa-chevron-left"></span></button><a class="btn btn-sm btn-falcon-default text-primary me-2" href="#!">1</a><a class="btn btn-sm btn-falcon-default me-2" href="#!">2</a><a class="btn btn-sm btn-falcon-default me-2" href="#!"><span class="fas fa-ellipsis-h"></span></a><a class="btn btn-sm btn-falcon-default me-2" href="#!">35</a>
              <button class="btn btn-falcon-default btn-sm" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Next"><span class="fas fa-chevron-right"></span></button>
            </div>
          </div>

{%endblock%}